default_title: "Le Wagon Events"
meta_description: "Classé parmi les 10 meilleurs bootcamp du monde, Le Wagon propose aux entrepreneurs des initiations au code via un panel d'événements : product punch, workshops et apérotalks."
meta_image: "lewagon_card.jpg"
meta_favicon: "favicon.png"
